### ISSUE TITLE
Action to test on MacOS

### ISSUE THREAD

**Issue by cvvergara** [MobilityDB/MobilityDB#107]
Create an action to test on macos

**Comment by estebanzimanyi** [comment]
Added an initial action based on the corresponding pgRouting action.
https://github.com/estebanzimanyi/MobilityDB/runs/3214085397?check_suite_focus=true
Fails on finding PostGIS

**Comment by cvvergara** [comment]
Because the postgis that it installs is version 3.x and the required is 2.5
But I am working on it because not only mobilitydb does not use boost, but it needs other things that need to be installed.
And need to figure out how they are installed, and also, becuase its apple thingy the CMakeLists might need an adjustment
So, skipping the postgis version issue, everything else should work. I am working on the details.
https://github.com/cvvergara/MobilityDB/tree/macos-action

**Comment by cvvergara** [comment]
Are you mixing PR for solving issues?
I tried to find the PR where you added the macos action without it been fully tested.
These are the new commits and non mention the macos action.
```
git log upstream/develop 
commit e3ee14ce45840bd1bd07ac796faadfc4654cd948 (upstream/develop)
Merge: 26159693 482992a9
Author: Esteban Zimanyi <esteban.zimanyi@ulb.be>
Date:   Sun Aug 1 12:12:55 2021 +0200

    Merge pull request #112 from estebanzimanyi/develop
    
    Improve documentation for enabling translations

commit 482992a93aee837f1c86504bf3cc7640115df97c
Author: Esteban Zimanyi <ezimanyi@ulb.ac.be>
Date:   Sun Aug 1 11:16:57 2021 +0200

    Improve documentation for enabling translations

commit 5d578ebf724e92143289ae95bccd097b94b3a729
Author: Esteban Zimanyi <ezimanyi@ulb.ac.be>
Date:   Sun Aug 1 11:13:22 2021 +0200

    Improve documentation for enabling translations

commit 26159693ea019038a04e602bf64a18d5db30c2b6
Merge: a61c8862 b58314a1
Author: Esteban Zimanyi <esteban.zimanyi@ulb.be>
Date:   Fri Jul 30 17:11:45 2021 +0200

    Merge pull request #110 from estebanzimanyi/develop
    
    Add .pot and .po files for the manual

commit b58314a1d6be4cba6f3f198d8e2c883c3faa63c8
Author: Esteban Zimanyi <ezimanyi@ulb.ac.be>
Date:   Fri Jul 30 16:46:50 2021 +0200

    Add .pot and .po files for the manual
```

**Comment by cvvergara** [comment]
Ah, no, sorry my mistake.
It was a branch you gave, (I saw develop and thought of mai repo, forgot you dont create working branches per issue)

**Comment by estebanzimanyi** [comment]
In my personal fork there is a branch postgis3 in which I tested the required changes to compile MobiliryDB with PostGIS 3 provided the liblwgeom headers are exported. You can find the changes by searching for the string "#ifdef POSTGIS3". 

The main changes correspond to a variable name change in the GSERIALIZED struct from flags to gflags 
```
#ifdef POSTGIS3
    if (FLAGS_GET_Z(sorigin->gflags))
#else
    if (FLAGS_GET_Z(sorigin->flags))
#endif
```
In addition a few internal functions have been removed or replaced
```
#ifdef POSTGIS3
  // gserialized_error_if_srid_mismatch(g1, g2, __func__);
  ensure_same_srid(gserialized_get_srid(g1), gserialized_get_srid(g2));
#else
  error_if_srid_mismatch(gserialized_get_srid(g1), gserialized_get_srid(g2));
#endif
```
Obviously it has not been fully tested and I stopped this work since I was blocked, and this is why I sent the message to the postgis-devel mailing list
https://lists.osgeo.org/pipermail/postgis-devel/2021-June/029006.html

**Comment by cvvergara** [comment]
I asked @robe2  and that is not going to happen:

>  provided the liblwgeom headers are exported

The headers will not be exported.

**Comment by cvvergara** [comment]
Closing issue, as the PR has been merged.
The action does not pass as in Macos the version of postgis that is installed is 3 and libwgeom 3 does not have headers.

**Comment by robe2** [comment]
Correct PostGIS project decided a while ago not to export the liblwgeom.  That is a no go for the PostGIS project which is why we created the librtopo fork of liblwgeom - https://git.osgeo.org/gitea/rttopo/librttopo so we don't have to worry about downstream dependencies on our underwear :)
