### ISSUE TITLE
Action to generate the documentation automatically

### ISSUE THREAD

**Issue by cvvergara** [MobilityDB/MobilityDB#116]
For example:
https://github.com/pgRouting/pgrouting/blob/main/.github/workflows/publish-users-doc.yml

That action generates the documentation and updates the documentation website on the gh-pages automatically

**Comment by cvvergara** [comment]
Looks like #117 must be done first

**Comment by mschoema** [comment]
The documentation is now being built and published automatically on gh-pages:
https://mobilitydb.github.io/MobilityDB/

This is being done for both the [user documentation](https://github.com/MobilityDB/MobilityDB/blob/master/.github/workflows/generate_docs.yml) as well as the [developer documentation](https://github.com/MobilityDB/MobilityDB/blob/master/.github/workflows/generate_dev_docs.yml).
Links to the different documentation versions are also present in the README.
