### ISSUE TITLE
Winnie build and packaging

### ISSUE THREAD

**Issue by cvvergara** [MobilityDB/MobilityDB#132]
The build that @robe2 is doing on winnie are based on the CMakeLists.txt is

https://github.com/cvvergara/MobilityDB/blob/add-winnie/CMakeLists.txt

this branch that is the one that @robe2 is using:
https://github.com/cvvergara/MobilityDB/tree/add-winnie

And the work is done in:
https://winnie.postgis.net:444/view/MobilityDb/

I am in constant communication with @robe2, to make adjustments to the scripts & cmake files (CMakeLists.txt)

A commit that will revert changes that happened on https://github.com/MobilityDB/MobilityDB/commit/3ee2c52b117158165206b5584748e3914442088a is in the PR #131 

Do not distub the build while we work on this

**Comment by cvvergara** [comment]
Also the CMakeLists.txt is on PR #133
But whatever the outcome is, the one on #133 will prevail

**Comment by estebanzimanyi** [comment]
Please take into account this comment
https://github.com/MobilityDB/MobilityDB/pull/131#discussion_r684615693
