### ISSUE TITLE
Using Postigis 3

### ISSUE THREAD

**Issue by cvvergara** [MobilityDB/MobilityDB#159]
First problem:

- PostGIS 3 does not have `getSRSbySRID` see this commit https://github.com/postgis/postgis/commit/b38079d4f1fac448c2a23681034521464d743cb6
  - was moved to the now non exposed `liblwgeom` which is no longer available on version 3 

```
mobtest=# CREATE FUNCTION period_in(cstring)
mobtest-#   RETURNS period
mobtest-#   AS '/home/vicky/mobilitydb/mobilitydb/cvvergara/build/libMobilityDB-1.0.so'
mobtest-#   LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;
NOTICE:  return type period is only a shell
ERROR:  could not load library "/home/vicky/mobilitydb/mobilitydb/cvvergara/build/libMobilityDB-1.0.so": /home/vicky/mobilitydb/mobilitydb/cvvergara/build/libMobilityDB-1.0.so: undefined symbol: getSRSbySRID
```

**Comment by cvvergara** [comment]
After having that function ported to mobilitydb
Now the error is:
```
ERROR:  could not load library "/home/vicky/mobilitydb/mobilitydb/cvvergara/build/libMobilityDB-1.0.so": /home/vicky/mobilitydb/mobilitydb
/cvvergara/build/libMobilityDB-1.0.so: undefined symbol: PostgisCacheContext
```

**Comment by cvvergara** [comment]
After adding that function now I get
```
ERROR:  could not load library "/home/vicky/mobilitydb/mobilitydb/cvvergara/build/libMobilityDB-1.0.so": /home/vicky/mobilitydb/mobilitydb
/cvvergara/build/libMobilityDB-1.0.so: undefined symbol: postgis_initialize_cache
```

**Comment by cvvergara** [comment]
Gradually this is becoming a copy of;
https://github.com/postgis/postgis/blob/stable-3.1/libpgcommon/lwgeom_pg.h
https://github.com/postgis/postgis/blob/f6def67654c25d812446239036cee44812613748/libpgcommon/lwgeom_pg.c
will try another approach

**Comment by estebanzimanyi** [comment]
Now the build with PostgreSQL 14 and PostGIS 3 are part of our CI workflow
https://github.com/MobilityDB/MobilityDB/actions/runs/1345278473
