### ISSUE TITLE
temporal interpolation and temporal sequence

### ISSUE THREAD

**Issue by wendellwt** [MobilityDB/MobilityDB#169]
Sirs,
I would like some advice.  I think I'm somehow getting data inserted as an 'instance set' instead of a 'sequence' (or something like that seems to be the issue).
When I insert data from the example:
```
INSERT INTO Trips VALUES
(20, 1, tgeompoint '[Point(0 0)@2012-01-01 08:05:00, Point(1 1)@2012-01-01 08:10:00, Point(3 3)@2012-01-01 08:20:00]');

```
and then try a spatial intersection, the interpolation happens as expected:
```
SELECT CarId, TripId, period(atValue(tintersects(Trip,
                               geometry 'POLYGON((0 0, 2.52 0, 2.52 2.52, 0 2.52, 0 0))'
                               ), TRUE)) as poly_exit
FROM Trips;
 carid | tripid |                    poly_exit
-------+--------+--------------------------------------------------
    20 |      1 | [2012-01-01 08:05:00+00, 2012-01-01 08:17:36+00]
(1 row)
```
The polygon boundary is between the points, and 08:17:36 seems right.
However, when I insert my own data:
```
INSERT INTO Trips VALUES (1432, 1432,
    tgeompoint '[POINT(-89.96667 35.01667)@2021-10-09 09:16:00+00, POINT(-89.96667 34.96667)@2021-10-09 09:18:00+00, POINT(-89.15 35.23333)@2021-10-09 09:25:00+00, POINT(-89.01667 35.28333)@2021-10-09 09:27:00+00, POINT(-88.83333 35.35)@2021-10-09 09:28:00+00]'
);
```
and try to do a spatial/temporal intersection, it seems to only return points, and doesn't interpolate:
```
SELECT CarId, TripId, period(atValue(tintersects(Trip,
        geometry 'POLYGON((-89.32992029558305 35.69159250963766, -89.00555829854898 35.21793835130748, -89.61472595151538 34.86168375396615, -90.41376404176998 34.894134683978564, -90.22389360448177 35.6594596006108, -89.32992029558305 35.69159250963766))'
                               ), TRUE)) as poly_exit
FROM Trips;
 carid | tripid |                    poly_exit
-------+--------+--------------------------------------------------
    20 |      1 |
  1432 |   1432 | [2021-10-09 09:16:00+00, 2021-10-09 09:25:00+00]
(2 rows)
```
How do I get MDB to interpolate (both spatial and temporal) to output the actual time of polygon exit?

Thank you,
Wendell

**Comment by wendellwt** [comment]
I'm using whatever the master was on Sep 3.  Should I install this:

`git clone --branch develop https://github.com/MobilityDB/MobilityDB.git
`

As I noticed before, in order to upgrade an extension in PostGreSQL, it requires dropping the current extension, and in doing so PostGreSQL deletes all of the tables (or columns) that the extension (Mdb) had created.

I would need to create a pg_dump of the entire database, switch out the MobilityDB extension, and pg_restore the entire database.  That will be fine, if we think that doing so will correct this issue.

**Comment by estebanzimanyi** [comment]
Alas, we know very well this problem when upgrading to a new version of MobilityDB. That would be our next topic of reflection for the next beta.

**Comment by wendellwt** [comment]
Ok, I'm looking forward to that.  Thank you.

**Comment by estebanzimanyi** [comment]
I am finalizing the changes, including in the documentation, that must arrive at the develop branch. I will tell you ASAP when I will finish

**Comment by wendellwt** [comment]
Thank you.

**Comment by wendellwt** [comment]
Great!  I'm making backups of my d.b. now and will check out beta4 as soon as I can.

The part about `asMVTGeom` looks interesting and I'm eager to try that out.
