### ISSUE TITLE
beta4 release availability (building) issues

### ISSUE THREAD

**Issue by ATTandT** [MobilityDB/MobilityDB#175]
Dear developers,

I tried to download and use the new beta4 release but it seems that for all its different forms (docker, workshop's version, building from git download) I get some issues: 

docker versions:
-liblwgeom-dev issues: library isn't found by directly using docker pull/build builds, it seems that is missing from some dockerfiles
-when docker builds were fixed (or I used the workshop's version) it seems that for all the cases the beta3 version is constructed

For working docker versions I checked the mobilitydb version number, the response was for all the cases returned as beta3.
I also tried to use different examples from the manual, the newer functions were not recognized by the DB.

building from source:
-it seems that an old problem re-appeared: 'create extension mobilitydb cascade' fails, workaround (suggested in #15) also fails
So I wasn't able to get a working MobilityDB beta4 for this case.

Can you point out what I'm doing wrongly? Or there is an issue with the release in the github?

Thank you for your help,
/Attila

**Comment by ATTandT** [comment]
After more digging I found out that the docker version I built from develop version works fine, containing the latest beta4 version. Here I made a mistake with the docker run cmd.
However, the other issues remain, namely with the workshop docker version and the one built from scratch.

**Comment by estebanzimanyi** [comment]
Dear Attila
We are beginning to work on this issue and let you know ASAP. In the meantime, maybe you can try to build MobilityDB from sources to avoid using docker. This should work in many possible version combinations, which are included in the regression tests, as can be seen e.g., in https://github.com/MobilityDB/MobilityDB/actions/runs/1429301569
Please let us know if you have any problem with the build.
Regards

**Comment by mbakli** [comment]
Dear @ATTandT,

Thank you for pointing out this issue, It has been fixed!. You can download the latest docker image which contains MobilityDB beta4 with PostgreSQL 14.1 and PostGIS 3.1.4.

docker pull mobilitydb/mobilitydb
docker volume create mobilitydb_data
docker run --name "mobilitydb" -d -p 25432:5432 -v mobilitydb_data:/var/lib/postgresql mobilitydb/mobilitydb
psql -h localhost -p 25432 -d mobilitydb -U docker

mobilitydb=# select mobilitydb_full_version();
                             mobilitydb_full_version                              
----------------------------------------------------------------------------------
 MobilityDB 1.0.0 beta4, PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1), PostGIS 3.1.4
(1 row)

If you have any questions or problems do not hesitate to contact us and we’ll be happy to help.

Best Regards,
Mohamed
