### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by infotek** [MobilityDB/MobilityDB#176]
Has anyone done a build to use on PostgreSQL on Windows x64 platform?

**Comment by estebanzimanyi** [comment]
Alas, we haven't had time to solve this issue. More precisely, we currently don't have someone in the team with experience on this topic. We started looking at mingw64 and actually the base code compiles without any problem but what we haven't had time continue this work to connect it with Visual Studio. Any help in this respect would be highly appreciated.

**Comment by robe2** [comment]
@infotek  I'm working on one. I plan to include it as part of PostGIS 3.3.0 Windows Bundle (via application stack builder), but hope to have experimental builds before then for people to try.

**Comment by estebanzimanyi** [comment]
Many thanks Regina for your commitment to MobilityDB !

Esteban

**Comment by apiszcz** [comment]
Regina, thank you, perhaps mobilitydb will be part of PostGIS soon.

**Comment by estebanzimanyi** [comment]
I was finally able to generate a Windows extension using MSYS2
https://github.com/estebanzimanyi/MobilityDB/blob/windows/.github/workflows/windows_msys2.yml
https://github.com/estebanzimanyi/MobilityDB/actions/runs/4671406939/jobs/8272354141
While doing this in my local machine I ended up with the following files in the build directory 
```
Esteban@DESKTOP-9FBND60 UCRT64 ~/MobilityDB/build
$ ls -al
total 2722
drwxr-xr-x 1 Esteban None       0 Apr 11 22:38 .
drwxr-xr-x 1 Esteban None       0 Apr 11 20:39 ..
-rw-r--r-- 1 Esteban None  456012 Apr 11 22:38 .ninja_deps
-rw-r--r-- 1 Esteban None   50111 Apr 11 22:38 .ninja_log
-rw-r--r-- 1 Esteban None   26727 Apr 11 22:36 CMakeCache.txt
drwxr-xr-x 1 Esteban None       0 Apr 11 22:38 CMakeFiles
-rw-r--r-- 1 Esteban None     350 Apr 11 22:36 CTestTestfile.cmake
-rw-r--r-- 1 Esteban None    2722 Apr 11 22:36 DartConfiguration.tcl
drwxr-xr-x 1 Esteban None       0 Apr 11 22:36 Testing
-rw-r--r-- 1 Esteban None  474215 Apr 11 22:36 build.ninja
-rw-r--r-- 1 Esteban None    1945 Apr 11 22:36 cmake_install.cmake
drwxr-xr-x 1 Esteban None       0 Apr 11 22:36 doc
drwxr-xr-x 1 Esteban None       0 Apr 11 22:36 doxygen
-rwxr-xr-x 1 Esteban None 2178801 Apr 11 22:38 libMobilityDB-1.1.dll
drwxr-xr-x 1 Esteban None       0 Apr 11 22:36 mobilitydb
-rw-r--r-- 1 Esteban None 1127332 Apr 11 22:36 mobilitydb--1.1.0.sql
-rw-r--r-- 1 Esteban None     178 Apr 11 22:36 mobilitydb.control
-rw-r--r-- 1 Esteban None 1277092 Apr 11 22:36 test_mobilitydb--1.1.0.sql
-rw-r--r-- 1 Esteban None 1277092 Apr 11 22:36 test_mobilitydb--1.1.0.sql.in

Esteban@DESKTOP-9FBND60 UCRT64 ~/MobilityDB/build
```
@robe2 How to do add the above files in the right directories on the preinstalled PostgreSQL and PostGIS installed using the EDB installers ? 
https://www.enterprisedb.com/downloads/postgres-postgresql-downloads
That is, what is the equivalent in Windows of `sudo make install` in Linux ?

**Comment by estebanzimanyi** [comment]
The windows build with MSYS2 is now on the develop branch !

**Comment by robe2** [comment]
I have preliminary builds for people to test for PG14 and PG15.  It should work fine if you are running with latest PostGIS Bundle release.  Just copy the same folder files into your C:\Program Files\PostgreSQL\15 (or 14 folder)

PG 14:
https://winnie.postgis.net/download/windows/pg14/buildbot/extras/mobilitydb-pg14-binaries-developw64gcc81.zip

PG 15:
https://winnie.postgis.net/download/windows/pg15/buildbot/extras/mobilitydb-pg15-binaries-developw64gcc81.zip

**Comment by robe2** [comment]
I was able to compile PG13 as well, but PG12 gives an error.  Develop should work with PG12 right?

```
[ 97%] Linking C shared module ../libMobilityDB-1.1.dll
cd /C/ming64gcc81/projects/mobilitydb/branches/MobilityDB/build/mobilitydb && /C/Projects/cmake-3.23.1-windows-i386/bin/cmake.exe -E rm -f CMakeFiles/MobilityDB-1.1.dir/objects.a
cd /C/ming64gcc81/projects/mobilitydb/branches/MobilityDB/build/mobilitydb && /C/ming64gcc81/mingw64/bin/ar.exe qc CMakeFiles/MobilityDB-1.1.dir/objects.a @CMakeFiles/MobilityDB-1.1.dir/objects1.rsp
cd /C/ming64gcc81/projects/mobilitydb/branches/MobilityDB/build/mobilitydb && /C/ming64gcc81/mingw64/bin/gcc.exe -O3 -DNDEBUG -O2 -shared -o ../libMobilityDB-1.1.dll -Wl,--major-image-version,0,--minor-image-version,0 -Wl,--whole-archive CMakeFiles/MobilityDB-1.1.dir/objects.a -Wl,--no-whole-archive @CMakeFiles/MobilityDB-1.1.dir/linklibs.rsp
CMakeFiles/MobilityDB-1.1.dir/objects.a(pg_types.c.obj):pg_types.c:(.text+0x104): undefined reference to `float_overflow_error'
CMakeFiles/MobilityDB-1.1.dir/objects.a(pg_types.c.obj):pg_types.c:(.text+0x214): undefined reference to `float_overflow_error'
CMakeFiles/MobilityDB-1.1.dir/objects.a(pg_types.c.obj):pg_types.c:(.text+0x2a4): undefined reference to `float_overflow_error'
CMakeFiles/MobilityDB-1.1.dir/objects.a(pg_types.c.obj):pg_types.c:(.text+0x340): undefined reference to `float_overflow_error'
collect2.exe: error: ld returned 1 exit status
```

**Comment by robe2** [comment]
All set.. Rebuilding my PG12 and then rebuilding mobilitydb against that seemed to fix the issue.

So I have PG12 - PG15 built now

https://winnie.postgis.net/download/windows/pg12/buildbot/extras/mobilitydb-pg12-binaries-developw64gcc81.zip

https://winnie.postgis.net/download/windows/pg13/buildbot/extras/mobilitydb-pg13-binaries-developw64gcc81.zip

PG 14:
https://winnie.postgis.net/download/windows/pg14/buildbot/extras/mobilitydb-pg14-binaries-developw64gcc81.zip

PG 15:
https://winnie.postgis.net/download/windows/pg15/buildbot/extras/mobilitydb-pg15-binaries-developw64gcc81.zip

I also added details of it on the postgis.net windows page - https://postgis.net/documentation/getting_started/install_windows/enabling_postgis/

So I think we can close this out.

**Comment by estebanzimanyi** [comment]
HUGE thanks to @robe2 for solving this issue. 
We are really grateful for all the time you worked on making MobilityDB available for Windows !
