### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by zacharywhitley** [MobilityDB/MobilityDB#178]
**Describe the bug**
When running `docker-compose up -d` I get a build error (see below)

**To Reproduce**
checkout 
cd 12-2.5-develop
docker-compose up -d

3.  See error

FindGEOS.cmake: geos-config not found. Please set it manually. GEOS_CONFIG=GEOS_CONFIG-NOTFOUND
GEOS_INCLUDE_DIR=
GEOS_LIBRARY=
CMake Error at cmake/FindGEOS.cmake:200 (MESSAGE):
  Could not find GEOS
Call Stack (most recent call first):
  CMakeLists.txt:126 (find_package)

-- Configuring incomplete, errors occurred!
See also "/usr/local/src/MobilityDB/build/CMakeFiles/CMakeOutput.log".
ERROR: Service 'mobilitydb' failed to build: The command '/bin/sh -c cd /usr/local/src/MobilityDB/build && 	cmake .. && 	make && 	make install' returned a non-zero code: 1

**Expected behavior**
build completes

**Comment by zacharywhitley** [comment]
Looks like adding libgeos-dev to the list of install prerequisites in the Dockerfile ie. apt-get install -y ... libgeos-dev ...., fixes things up.

**Comment by mbakli** [comment]
Dear @zacharywhitley,

Many thanks for figuring out this issue. It is indeed a problem in the docker image and we already fixed it but we did not push the new modications to github, I expect by the next week all the images will be updated and work properly.

You can use the latest docker image which contains MobilityDB Beta4 with PostgreSQL 14 and PostGIS 3.1 using the following commands:

docker pull mobilitydb/mobilitydb
docker volume create mobilitydb_data
docker run --name "mobilitydb" -d -p 25432:5432 -v mobilitydb_data:/var/lib/postgresql mobilitydb/mobilitydb
psql -h localhost -p 25432 -d mobilitydb -U docker

The beta4 version has many improvements and new features.

Please let us know if you need any other help!

Best Regards,
Mohamed

**Comment by zacharywhitley** [comment]
Many thanks. I'm enjoying exploring MobilityDB and I'll let you know if I come across anything else.
