### ISSUE TITLE
mvt examples?

### ISSUE THREAD

**Issue by wendellwt** [MobilityDB/MobilityDB#179]
How is asMVTGeom used in a web server?  Are there examples of its use?

Is `SELECT asMVTGeom(...)` a drop-in replacement to the `SELECT ST_AsMVTGeom(...)` part of the pg_tileserv example shown at [Filtering Example](https://github.com/CrunchyData/pg_tileserv#filtering-example)  as used in pg_tileserv?

If using OpenLayers, should the `bounds` argument be the extent of the viewport / window, which is `olmap.getView().calculateExtent(olmap.getSize());`?

Thank you.

**Comment by wendellwt** [comment]
Ok, I'm getting a little closer.  It seems that I need to only use the geom, not the times :-(
At least something shows up (but not in the right place).
```
CREATE OR REPLACE
FUNCTION public.fvf_tracks(
            z integer, x integer, y integer,
            arr_apt text default 'DFW')
RETURNS bytea
AS $$
    WITH
    bounds AS (
      SELECT ST_TileEnvelope(z, x, y) AS geom
    ),
    mvtgeom AS (
      -- ++++++++++++++++++++++++++++++++++++
    SELECT (mvt).geom as geom FROM (
      SELECT asMVTGeom(flown_path::tgeompoint, stbox 'STBOX((-120,30),(-75,55))') AS mvt
            FROM flown_m4_2021_08
            WHERE opsday = '2021-08-16'
            AND dep_apt ='CLT' AND arr_apt='DFW') AS t
    -- ++++++++++++++++++++++++++++++++++++++++++++++++
    )
    SELECT ST_AsMVT(mvtgeom, 'public.fvf_tracks') FROM mvtgeom;
$$
LANGUAGE 'sql'
STABLE
PARALLEL SAFE;
```
The stbox shown here is completely wrong.  Where do I get the proper bounds for stbox?

**Comment by estebanzimanyi** [comment]
Dear Webdell
Maybe you could take a look at 
https://github.com/MobilityDB/MobilityDB-Deck
which is a Master's Thesis of a student in which we develop the asMVTGeom functionality. This work should be still be fully integrated into MobilityDB and add the documentation but it works very well when visualizing large number of moving objects as shown in the animation of the README.md file.
Please let me know whether you have any question in this respect.
Regards
Esteban

**Comment by estebanzimanyi** [comment]
A Master student topic on this topic has been published
https://github.com/MobilityDB/MobilityDB-OpenLayers
