### ISSUE TITLE
Improve Code Quality

### ISSUE THREAD

**Issue by mschoema** [MobilityDB/MobilityDB#199]
The functions _tpointseqarr_stbox_ and _tnpointseqarr_stbox_ do the exact same thing and could be merged into a single function. 

https://github.com/MobilityDB/MobilityDB/blob/d4ca7ecbfff3458029b01626988bcec6d7519588/src/point/tpoint_boxops.c#L182-L192

https://github.com/MobilityDB/MobilityDB/blob/d4ca7ecbfff3458029b01626988bcec6d7519588/src/npoint/tnpoint_boxops.c#L174-L184

This might be possible with other functions, but I didn't check that yet.

**Comment by mschoema** [comment]
Uniformize the *__make_free_ functions.

https://github.com/MobilityDB/MobilityDB/blob/f4f825715876186760624dab9f5eac583d141d92/src/general/tinstantset.c#L200-L207

https://github.com/MobilityDB/MobilityDB/blob/f4f825715876186760624dab9f5eac583d141d92/src/general/tsequence.c#L718-L722

https://github.com/MobilityDB/MobilityDB/blob/f4f825715876186760624dab9f5eac583d141d92/src/general/tsequenceset.c#L194-L201

**Comment by mschoema** [comment]
The definition of the function _tinstant_to_tinstantset_ in _tinstant.h_ is a copy of the one in _tinstantset.h_ and should be removed.

https://github.com/MobilityDB/MobilityDB/blob/d4ca7ecbfff3458029b01626988bcec6d7519588/include/general/tinstant.h#L81

https://github.com/MobilityDB/MobilityDB/blob/d4ca7ecbfff3458029b01626988bcec6d7519588/include/general/tinstantset.h#L93

**Comment by estebanzimanyi** [comment]
Solved by PR #201
