### ISSUE TITLE
Can't create extension in PostgreSQL 15, undefined symbol: pg_atoi

### ISSUE THREAD

**Issue by robe2** [MobilityDB/MobilityDB#218]
**Describe the bug**
PG15 removed the pg_atoi function, as a result though the extension compiles, the tests fail.
I tried both the develop branch and v1.0 branch.  v1.0 gives a warning notice about pg_atoi early on, but compiles.  develop doesn't give a warning notice.

When you go to CREATE EXTENSION mobilitydb;

It gives this error:

ERROR:  could not load library "/usr/lib/postgresql/15/lib/libMobilityDB-1.0.so": /usr/lib/postgresql/15/lib/libMobilityDB-1.0.so: undefined symbol: pg_atoi
SQL state: 58P01

**To Reproduce**
1. Install PostgreSQL 15 beta1 (I installed on Arm64 Ubuntu Jammy) using apt.postgresql.org repo
2.  Building Mobilitydb as usual (using develop or v1.0)
3.  Log into a database and do
`CREATE EXTENSION mobilitydb;`

**Expected behavior**
It should install the extension

**Specifications (please complete the following information):**
Use the commands:
```SQL
SELECT version();
SELECT postgis_full_version();
```
```
PostgreSQL 15beta1 (Ubuntu 15~beta1-1.pgdg22.04+1) on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, 64-bit

"POSTGIS=""3.3.0dev 0"" [EXTENSION] PGSQL=""150"" GEOS=""3.10.2-CAPI-1.16.0"" PROJ=""8.2.1"" LIBXML=""2.9.13"" LIBJSON=""0.15"" LIBPROTOBUF=""1.3.3"" WAGYU=""0.5.0 (Internal)"" TOPOLOGY"
```

**Additional context**
We had the same issue in PostGIS -- the bug and fix is here - https://trac.osgeo.org/postgis/ticket/5100

**Comment by estebanzimanyi** [comment]
Fixed in the develop version
https://github.com/MobilityDB/MobilityDB/blob/develop/src/point/tpoint.c#L49
