### ISSUE TITLE
QGIS integration

### ISSUE THREAD

**Issue by apiszcz** [MobilityDB/MobilityDB#222]
Do we expect a native or plugin to visualize the MobilityDB geometry/time features in a more natural / QGIS way.

The move plugin is interesting, I'm curious if there are discussions or plans to handle MobilityDB natively in QGIS?

Thanks

**Comment by estebanzimanyi** [comment]
Although we are planning to handle MobilityDB types natively in QGIS in the future, this is not in the current tasks that we are working on.

There are technical reasons for this that have been explored in the following Master's student project
https://github.com/ludericv/MobilityDB-visualization
but we haven't found a way to solve these issues.

Any help with this would be highly appreciated!

In the meantime, we are working on alternative approaches using Open Layers
https://github.com/MobilityDB/MobilityDB-OpenLayers
and using Deck.gl
https://github.com/MobilityDB/MobilityDB-Deck

Regards

Esteban
