### ISSUE TITLE
QGIS interactive visualization tool, QTDC

### ISSUE THREAD

**Issue by apiszcz** [MobilityDB/MobilityDB#227]
There is a QGIS plugin which may be of interest.
The QGIS Time Data Controller enables QGIS to interactively visualize vector data, trajectories, etc.
https://github.com/mitre/QgisTDC
The compiled plugin is available in the 'build' folder.

**Comment by mschoema** [comment]
Currently, the Move plugin uses the native QGIS temporal controller to animate moving object data.
Looking at the plugin it is not clear what the benefits are of using this compared to the native temporal controller.
https://anitagraser.com/2020/05/10/timemanager-is-dead-long-live-the-temporal-controller/
https://github.com/qgis/QGIS/pull/36243

Do you have any insights into what the differences are between the two?

**Comment by apiszcz** [comment]
Performance, try both.
________________________________

**Comment by anitagraser** [comment]
Thanks for the pointer, @apiszcz. Are there any demos of QTDC and / or a comparison with Temporal Controller?

**Comment by apiszcz** [comment]
Hello not yet. We tried all other controllers and found them slow in render performance for our use cases. We need a community benchmark for render performance of time data controllers.

**Comment by apiszcz** [comment]
BTW: a quick example with QGIS temporal controller and QTDC is here
https://github.com/mschoema/move/issues/5

**Comment by anitagraser** [comment]
Thank you for sharing, @apiszcz. The GUI of QTDC makes a good first impression. 

Since you mentioned Temporal Controller performance as an issue, I would like to see a performance comparison because I have a hard time imagining how QTDC can have better rendering performance since both rely on QGIS to render the features. Are you aware that the Temporal Controller settings have controls to make the animation faster?

**Comment by apiszcz** [comment]
No I am not. other than change the step interval. The experience is different.

**Comment by abroniewski** [comment]
Hi @apiszcz! I was actually working on a dashboard on Grafana and also had frustrations with the lack of a comprehensive visualization method for trajectory data.

I'm working with MobilityDB to explore a commercial or enterprise level offering, and would love to learn more about what you are working on and what types of issues or hardships you're experiencing in your work with spatiotemporal data. Shoot me a note to abroniewski@gmail.com if you're open to connect and chat further.
