### ISSUE TITLE
`asMVTGeom` producing incorrect timestamps

### ISSUE THREAD

**Issue by sabman** [MobilityDB/MobilityDB#234]
**Describe the bug**

Testing `asMVTGeom` the actual output is different from expected:

ref: https://docs.mobilitydb.com/MobilityDB/develop/ch05s12.html#idm3166

expected:

```sql
SELECT ST_AsText((mvt).geom), (mvt).times
FROM (SELECT asMVTGeom(tgeompoint '[Point(0 0)@2000-01-01, Point(100 100)@2000-01-02]',
  stbox 'STBOX((40,40),(60,60))') AS mvt ) AS t;
-- LINESTRING(-256 4352,4352 -256) | {946714680,946734120}
SELECT ST_AsText((mvt).geom), (mvt).times
FROM (SELECT asMVTGeom(tgeompoint '[Point(0 0)@2000-01-01, Point(100 100)@2000-01-02]',
  stbox 'STBOX((40,40),(60,60))', clip:=false) AS mvt ) AS t;
-- LINESTRING(-8192 12288,12288 -8192) | {946681200,946767600}
```

actual:
```sql
SELECT ST_AsText((mvt).geom), (mvt).times
FROM (SELECT asMVTGeom(tgeompoint '[Point(0 0)@2000-01-01, Point(100 100)@2000-01-02]',
  stbox 'STBOX((40,40),(60,60))') AS mvt ) AS t;
-- LINESTRING(-256 4352,4352 -256) | {"2000-01-01 00:15:46.71828+00","2000-01-01 00:15:46.73772+00"}
SELECT ST_AsText((mvt).geom), (mvt).times
FROM (SELECT asMVTGeom(tgeompoint '[Point(0 0)@2000-01-01, Point(100 100)@2000-01-02]',
  stbox 'STBOX((40,40),(60,60))', clip:=false) AS mvt ) AS t;
-- LINESTRING(-8192 12288,12288 -8192) | {"2000-01-01 00:15:46.6848+00","2000-01-01 00:15:46.7712+00"}
```

```diff
4c4
< -- LINESTRING(-256 4352,4352 -256) | {946714680,946734120}
---
> -- LINESTRING(-256 4352,4352 -256) | {"2000-01-01 00:15:46.71828+00","2000-01-01 00:15:46.73772+00"}
8c8
< -- LINESTRING(-8192 12288,12288 -8192) | {946681200,946767600}
---
> -- LINESTRING(-8192 12288,12288 -8192) | {"2000-01-01 00:15:46.6848+00","2000-01-01 00:15:46.7712+00"}
```
**To Reproduce**
Run the above example from official [documentation](https://docs.mobilitydb.com/MobilityDB/develop/ch05s12.html#idm3166)

**Specifications (please complete the following information):**
Use the commands:
```SQL
SELECT version();
                                        version
---------------------------------------------------------------------------------------
 PostgreSQL 13.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
(1 row)

SELECT postgis_full_version();
                                                                    postgis_full_version
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="3.0.3 0" [EXTENSION] PGSQL="130" GEOS="3.8.1-CAPI-1.13.3" PROJ="7.0.1" LIBXML="2.9.10" LIBJSON="0.14" LIBPROTOBUF="1.3.3" WAGYU="0.4.3 (Internal)"
(1 row)

SELECT mobilitydb_full_version();
             mobilitydb_full_version
--------------------------------------------------
 MobilityDB 1.0.0, PostgreSQL 13.1, PostGIS 3.0.3
(1 row)
```

**Additional context**

The time stamps should be epocs but are being returned as strings and are incorrect.

Here is the Dockerfile to build this environment

```dockerfile
FROM postgis/postgis:13-3.0-alpine

ENV MOBILITYDB_VERSION 1.0

RUN apk update && apk --no-cache  add cmake make gcc g++ libc-dev fortify-headers patch binutils file \
    wget \
    autoconf \
    geos-dev \
    proj-dev \
    json-c-dev \
    protobuf-c \
    gsl-dev 


# Install MobilityDB 
RUN wget -O MobilityDB.tar.gz "https://github.com/MobilityDB/MobilityDB/archive/v${MOBILITYDB_VERSION}.tar.gz" \
    && mkdir -p /usr/local/src/MobilityDB \
    && tar \
    --extract \
    --file MobilityDB.tar.gz \
    --directory /usr/local/src/MobilityDB \
    --strip-components 1 \
    && rm MobilityDB.tar.gz
RUN mkdir /usr/local/src/MobilityDB/build
RUN cd /usr/local/src/MobilityDB/build && \
    cmake .. && \
    make -j$(nproc) && \
    make install

COPY ./initdb-mobilitydb.sh /mobilitydb.sh
RUN chmod +x /mobilitydb.sh
```

and the `initdb-mobilitydb.sh` file

```sh
#!/bin/bash

echo "shared_preload_libraries = 'postgis-3.so'" >> $PGDATA/postgresql.conf

set -e

# Create the 'mobilitydb' extension in the mobilitydb database
echo "Loading MobilityDB extension into mobilitydb"
psql --user="$POSTGRES_USER" --dbname="$POSTGRES_DB" <<- 'EOSQL'
	CREATE EXTENSION IF NOT EXISTS mobilitydb CASCADE;
EOSQL
```

**Comment by estebanzimanyi** [comment]
Many thanks for reporting this issue. We have corrected it in the develop branch. Could you please verify whether everything works for you ?

**Comment by Hussnain47** [comment]
Just did a quick test on intel x64 architecture. Seems to work. It seems to have some issue on ARM architecture. @sabman is still doing some testing. Will report back.

**Comment by sabman** [comment]
I'm finding performance of the function using `asMVTGeom` on the ARM architecture (Mac M1) to be pretty poor, such that out tileserver timesout on making requests. 

Otherwise, on x86 it seems to have fixed the bug. Will close this for now, ARM performance could be another issue to address later. Let me know if you would like us to create something for that.

Here's a little demo for your viewing pleasure https://www.youtube.com/watch?v=gphSl3A0e9o 😃

**Comment by estebanzimanyi** [comment]
Many thanks for this amazing visualization !

It could be great if you can help us to solve the issue with the ARM
architecture. Alas, we don't have expertise in this area.

Regards

Esteban

------------------------------------------------------------
Prof. Esteban Zimanyi
Department of Computer & Decision Engineering  (CoDE) CP 165/15
Universite Libre de Bruxelles
Avenue F. D. Roosevelt 50
B-1050 Brussels, Belgium
fax: + 32.2.650.47.13
tel: + 32.2.650.31.85
e-mail: ***@***.***
Internet: http://cs.ulb.ac.be/members/esteban/
------------------------------------------------------------

**Comment by sabman** [comment]
yea definitely we can try. I'll keep you posted. but yea looking at the Mac's Docker Desktop we see this warning:
![Cursor_and_Container_list_and_Docker_Desktop](https://user-images.githubusercontent.com/1907/182883569-ffabd0d8-4297-4e25-b093-ceb59717f731.png)

**Comment by sabman** [comment]
For the record. For building on ARM64 machine simply set the following environment variable in your shell.
```sh
export DOCKER_DEFAULT_PLATFORM=linux/arm64
```
