### ISSUE TITLE
Editor Config

### ISSUE THREAD

**Issue by cvvergara** [MobilityDB/MobilityDB#24]
**Is your feature request related to a problem? Please describe.**
 EditorConfig, which is a file wherein one may define and then maintain a consistent coding style.
https://editorconfig.org/

**Describe the solution you'd like**
Have an editor config file that allows my editor to follow your coding style

**Describe alternatives you've considered**
https://editorconfig.org/

**Additional context**
Many files might need to be reconfigured based on the editor config specification

**Comment by estebanzimanyi** [comment]
Issue solved by PR #25
