### ISSUE TITLE
Document spelling errors.

### ISSUE THREAD

**Issue by apiszcz** [MobilityDB/MobilityDB#248]
(anoter -> another)
A.2.2 Casting
• tbox::type: Cast a tbox to another type
• type::tbox: Cast another type to a tbox
• stbox::type: Cast an stbox to anoter type
• type::stbox: Cast another type to an stbox

(bouding -> bounding)
A.2.7 Comparison Operators
• =: Are the bounding boxes equal?
• <>: Are the bounding boxes different?
• <: Is the first bouding box less than the second one?
• >: Is the first bouding box greater than the second one?
• <=: Is the first bouding box less than or equal to the second one?
• >=: Is the first bouding box greater than or equal to the second one?

**Comment by estebanzimanyi** [comment]
Many thanks ! I have corrected in my fork and will be on the develop branch in a few days.

**Comment by apiszcz** [comment]
Thanks, there are more, sorry passing them on as i bumped into them

A1.7
scritly -> strictly
• <<: Is the first number or range value scritly left of the second one?

**Comment by estebanzimanyi** [comment]
I think you are looking at the master branch, many things have changed
since then

Maybe you can envision working on the develop branch.
