### ISSUE TITLE
SRID is lost during serialization of STBOX, TGeomPoint etc.

### ISSUE THREAD

**Issue by LauJosefsen** [MobilityDB/MobilityDB#299]
**Describe the bug**
Hi again :)

I am a bit uncertain if this is intentional or not, or how the extend of the issue is, but I'll do my best to describe it. 

When using MobiltyDB with Citus, SRID is lost when objects are transferred/repartitioned between nodes.

It seems that serialization of geometric types, such as STBox and TGeomPoint (and most likely others) loose their SRID when serialized. It is also lost in the `AsText()` serialization, but I'm unsure how Citus serializes the objects?

We have a work around for the time being (`UPDATE table SET trajectory = SetSRID(trajectory, 4326)`, after every repartioning), but it would be very nice if it was solved without this work around.

**To Reproduce**
Let us use the trajectory which is defined as the type tgeompoint `SRID=4326;[POINT(12.198383000000002 55.46990299999999)@2021-01-23 18:39:11+00, POINT(12.198378000000002 55.469868000000005)@2021-01-23 18:46:56+00]`

```
SELECT SRID(tgeompoint 'SRID=4326;[POINT(12.198383000000002 55.46990299999999)@2021-01-23 18:39:11+00, POINT(12.198378000000002 55.469868000000005)@2021-01-23 18:46:56+00]')
-- 4326 - as expected

SELECT SRID(tgeompoint(AsText(tgeompoint 'SRID=4326;[POINT(12.198383000000002 55.46990299999999)@2021-01-23 18:39:11+00, POINT(12.198378000000002 55.469868000000005)@2021-01-23 18:46:56+00]')))
-- 0 - I would still expect 4326?
```

The same happens for STBox and possible other spatial types.

**Specifications (please complete the following information):**
Use the commands:
```SQL
SELECT version();
-- PostgreSQL 15.2 (Ubuntu 15.2-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit
SELECT postgis_full_version();
-- POSTGIS="3.3.2 4975da8" [EXTENSION] PGSQL="150" GEOS="3.10.2-CAPI-1.16.0" PROJ="8.2.1" GDAL="GDAL 3.4.1, released 2021/12/27" LIBXML="2.9.13" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)" RASTER
SELECT mobilitydb_full_version();
-- MobilityDB 1.1.0, PostgreSQL 15.2 (Ubuntu 15.2-1.pgdg22.04+1), PostGIS 3.3.2, GEOS 3.10.2-CAPI-1.16.0, PROJ 8.2.1
```

**Additional context**

**Comment by mschoema** [comment]
Hi, thank you for reporting this.

Firstly, concerning the behaviour of `AsText(),` this is expected.
Indeed, the `AsText()` function returns a simple textual representation of the object, which does not contain the SRID.
If you want a textual representation which contains the SRID, you should use `AsEWKT()` (Extended Well-Known Text).

The Citus part is more concerning, but I might have an idea about what is happening.
Each type has 2 I/O methods: A textual and a binary I/O.

The textual I/O is called when we return the type without any processing or when using `COPY` with default formatting. 
For example: `SELECT trip FROM trips;` (Note that this is not the same as calling `AsText()`)
Looking at the code, it seems that this method preserves the SRID.

On the other hand, the binary I/O seems to lose the SRID information and it is highly probably that this is what Citus uses internally. I have not used Citus with MobilityDB myself, so I am only guessing the last part, but this would explain the problem that you are having. 
This behavious is indeed a bug, as we want the objects to be exactly preserved after an I/O round-trip.
We will fix this in an upcoming pull request.

**Comment by LauJosefsen** [comment]
Hi again.

Thanks for quick reponse, and thanks for clarification of AsText and AsEWKT. 

According to Citus docs, the binary I/O should be used on PostgreSQL14+.

We have just tried building with the commit mentioned, and unfortunately we still have the issue.

This reproduces the issue:
```
CREATE TABLE foobar (
    id serial,
    trajectory tgeompoint
);

INSERT INTO foobar (trajectory) VALUES (tgeompoint 'SRID=4326;[POINT(12.198383000000002 55.46990299999999)@2021-01-23 18:39:11+00, POINT(12.198378000000002 55.469868000000005)@2021-01-23 18:46:56+00]');

SELECT srid(trajectory) FROM foobar;
-- 4326 as expected

SELECT create_reference_table('foobar');

SELECT srid(trajectory) FROM foobar;
-- 0

```

**Comment by mschoema** [comment]
Are you certain to have tested the correct code version (by starting from a clean build / restarting postgres / ...)?
Could it be that you tested it before the PR was merged?
I installed citus to test it out locally, and I have the following results (with the current develop branch).

```c
test=# select srid(p) from t1;
 srid 
------
 4326
(1 row)

test=# select create_reference_table('t1');
 create_reference_table 
------------------------
 
(1 row)

test=# select srid(p) from t1;
 srid 
------
 4326
(1 row)
```

**Comment by LauJosefsen** [comment]
Can confirm by clearing our build cache it is working now, sorry for the trouble and thanks for the fix!
