### ISSUE TITLE
Issues with installation instructions on Ubuntu 20.04.

### ISSUE THREAD

**Issue by Darrekt** [MobilityDB/MobilityDB#303]
**Describe the bug**
When trying to follow the [installation instructions](https://mobilitydb.com/install.html), the build fails. I am on a mostly fresh install of Ubuntu 20.04. I followed the steps exactly, installing the stated dependencies, and then proceeded to run the `git clone` and build instructions.

Additionally, I would note that the following 3 dependencies were missing during the `cmake` process, which I installed manually: `libgeos-dev pkg-config libgsl-dev`

```bash
ubuntu@server:~/MobilityDB/build$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

ubuntu@server:~/MobilityDB/build$ ls
CMakeCache.txt  cmake_install.cmake  DartConfiguration.tcl  doxygen   MobilityDB             mobilitydb.control  sql  test     test_mobilitydb--1.0.0.sql
CMakeFiles      CTestTestfile.cmake  doc                    Makefile  mobilitydb--1.0.0.sql  postgis             src  Testing  test_mobilitydb--1.0.0.sql.in

ubuntu@uat-dasec-citusdb:~/MobilityDB/build$ make
[  0%] Built target control
[  0%] Built target sqlscript
[  1%] Building C object src/npoint/CMakeFiles/npoint.dir/tnpoint.c.o
In file included from /home/ubuntu/MobilityDB/src/npoint/tnpoint.c:35:
/home/ubuntu/MobilityDB/include/npoint/tnpoint.h:39:10: fatal error: postgres.h: No such file or directory
   39 | #include <postgres.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/npoint/CMakeFiles/npoint.dir/build.make:63: src/npoint/CMakeFiles/npoint.dir/tnpoint.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1473: src/npoint/CMakeFiles/npoint.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

I can see from the output that it is looking for a header file, which I have been told from [this SO article](https://stackoverflow.com/questions/56724622/how-to-fix-postgres-h-file-not-found-problem), is contained in the `postgresql-server-dev-XX` package. 

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/44197672/227864708-164363e7-cfd4-4a47-bf6b-91bd2e367e70.png">

The mobilityDB docs state to install version 11, but my system has postgres 14 and 15 installed, of which I wish to install MobilityDB on the cluster run by 14. So I took the further liberty of installing `postgresql-server-dev-14` and restarting my shell, but to no avail.

Do I just need a sanity check here? Hopefully, this is constructive and someone can look at it. I'm happy to provide further debug information if someone can point me to the right place to look.

**To Reproduce**

```bash
git clone https://github.com/MobilityDB/MobilityDB
mkdir MobilityDB/build
cd MobilityDB/build
cmake ..
make
```

**Comment by estebanzimanyi** [comment]
Hi
We are planning to release version 1.1 of MobilityDB in the forthcoming months. Could you please try to install the develop version ? It is working on my laptop

esteban@DESKTOP-9FBND60:~/src/MobilityDB-BerlinMOD/BerlinMOD$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Please let us know whether this works for you.
