### ISSUE TITLE
Link to BerlinMOD is broken

### ISSUE THREAD

**Issue by maxbiostat** [MobilityDB/MobilityDB#362]
The following link: http://dna.fernuni-hagen.de/secondo/BerlinMOD/BerlinMOD.html 

appears to be broken.

**Comment by estebanzimanyi** [comment]
Many thanks for pointing out this. I have found that this is the new link
https://secondo-database.github.io/BerlinMOD/BerlinMOD.html

**Comment by maxbiostat** [comment]
Thanks!
