### ISSUE TITLE
mingw64 building of mobilitydb for PostgreSQL 16, CREATE EXTENSION fails

### ISSUE THREAD

**Issue by robe2** [MobilityDB/MobilityDB#366]
**Describe the bug**
This seems to be only an issue under mingw64 and with PG 16 specifically.  PG 15 for example is fine.

This is building the 1.1.0alpha package

I tested on debian and that seemed okay.

The extension builds under mingw64, but when I go to do 

```
CREATE EXTENSION mobilitydb;
```

I get an error

```
ERROR:  could not find function "Left_stbox_tnpoint" in file "C:/ming64gcc81/projects/postgresql/rel/pg16w64gcc81/lib/libMobilityDB-1.1.dll" 
```

**Specifications (please complete the following information):**
Use the commands:
```SQL
SELECT version();  
SELECT postgis_full_version();
-- can't run cause can't inatall
SELECT mobilitydb_full_version();
```

Output
```
                                                         version

-------------------------------------------------------------------------------------------------------------------------
--------
 PostgreSQL 16beta3 on x86_64-w64-mingw32, compiled by gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0,
 64-bit

 POSTGIS="3.4.0 3.4.0rc4-1-g07a11e15d" [EXTENSION] PGSQL="160" GEOS="3.12.0dev-CAPI-1.18.0" PROJ="8.2.1 NETWORK_ENABLED=O
FF URL_ENDPOINT=https://cdn.proj.org USER_WRITABLE_DIRECTORY=C:\Users\Administrator\AppData\Local/proj DATABASE_PATH=C:\m
ing64gcc81\projects\proj\rel-proj-8.2.1w64gcc81/share/proj/proj.db" LIBXML="2.9.14" LIBJSON="0.12" LIBPROTOBUF="1.2.1" WA
GYU="0.5.0 (Internal)"
(1 row)
```

**Additional context**
At a glance, I'm not seeing anything about how this function is defined that would cause this issue.  Even more surprising why it's fine on PG15.

Last time I had this issue I think was something about how the PGDLLIMPORT something about the ordering.

I'll see if I can nail down the issue.

**Comment by robe2** [comment]
Okay I think it might be all the functions,  I went thru a couple and then stopped cause it seemed all functions were impacted

```
Overleft_stbox_tnpoint
Right_stbox_tnpoint
Overright_stbox_tnpoint
Below_stbox_tnpoint
Overbelow_stbox_tnpoint
```

**Comment by robe2** [comment]
Okay CREATE EXTENSION worked after I move meos.h down.  I recall that's what I had to do last time I had this issue.

**Comment by estebanzimanyi** [comment]
Dear Regina
In the last commit for the develop branch we have added the following line
https://github.com/MobilityDB/MobilityDB/blob/develop/mobilitydb/src/npoint/tnpoint_posops.c#L47
thay may solve the problem.
Could you please confirm so we can put a tag on this version to facilitate your packaging task ?

**Comment by estebanzimanyi** [comment]
@robe2 
Kind reminder, please verify whether the problem is solved whenever you will have time.

**Comment by robe2** [comment]
@estebanzimanyi  Sorry about the delay.  Unfortunately I'm still building out my dev environment cause my old computer crashed beyond repair.  Please go ahead and release.  I already patched the PG16 for windows when I did this pull request before my computer crashed so wouldn't be able to do another bundle release for another month or so anyway.  At that time if there is an issue we can always fix in 1.1.1.

**Comment by robe2** [comment]
@estebanzimanyi  I tested develop branch and still run into the same issue with the missing functions.

As for the master branch, is that supposed to have 1.1.0 in it, the last commit says it does, but I can't compile that branch, reads Mobility-1.0.  The error I get is with the GEOS version parsing.

**Comment by estebanzimanyi** [comment]
Regina
I finally had time to look at the problem you reported. Is there any precompiled version of PostgreSQL 16 on MSYS2. The only one I have found is for version 15
https://packages.msys2.org/package/mingw-w64-x86_64-postgresql

**Comment by robe2** [comment]
> Regina I finally had time to look at the problem you reported. Is there any precompiled version of PostgreSQL 16 on MSYS2. The only one I have found is for version 15 https://packages.msys2.org/package/mingw-w64-x86_64-postgresql

Not sure.  I usually just build my own since I have to build for all postgresql supported versions. Let me put my latest build somewhere and then you can extract.  I need to update my instructions too and will provide that after I clean it up a bit.

**Comment by robe2** [comment]
Okay I have my pg16w64 binaries here - https://winnie.postgis.net/download/windows/buildchainlibs/pg16w64.zip
with that, to install PostGIS, extract https://winnie.postgis.net/download/windows/pg16/buildbot/postgis-pg16-binaries-3.4.0w64gcc81.zip and copy the contents into that pg16w64 folder.

To start it launch the pgstopstartplain.bat in the pg16w64 folder.

I also realized I was compiling pre PG16 release, so let me test again with the released PG16 before you waste your time.

**Comment by robe2** [comment]
It seems to be fine now with release PG16 and compiling against develop.  I can do ```CREATE EXTENSION mobilitydb;``` without my patch.
