### ISSUE TITLE
How to append a tgeompoint to its trajectory?

### ISSUE THREAD

**Issue by MineRiaaa** [MobilityDB/MobilityDB#446]
In MobilityDB, a trajectory is a series of tgeompoints, right? Then, if I have stored a trajectory in MobilityDB, the trajectory is still going ahead, so there should be more tgeompoints to be appended to the trajectory. How is this achieved? I have read the paper and documentation of MobilityDB; however, I failed to find the answer.

In short, I wonder how to realize real-time storage and update of a trajectory in MobilityDB.

Thanks!

**Comment by mschoema** [comment]
Hi,

Indeed, a single trajectory is usually stored as a single tgeompoint sequence, which is a series of tgeompoint instants.
If you have a table containing multiple trips / trajectories `Trips(id integer, trip tgeompoint)` and you want to add new points to a specific trip, you can do it using the `appendInstant` functions, which is part of the [modification operations](https://mobilitydb.github.io/MobilityDB/master/ch06.html#temporal_types_modifications) of MobilityDB.

For example, if you want to append the instant `'Point(12, 34)@2001-01-25'` to trajectory with `id = 5`, you could use the following query:
```sql
UPDATE Trips SET trip = appendInstant(trip, tgeompoint 'Point(12, 34)@2001-01-25') WHERE id = 5;
```

**Comment by MineRiaaa** [comment]
Thanks! In addition, when using the query
```
UPDATE Trips SET trip = appendInstant(trip, tgeompoint 'Point(12, 34)@2001-01-25') WHERE id = 5;
```
to append the instant `'Point(12, 34)@2001-01-25'` to trajectory with `id = 5`, do we find the specified trajectory by scanning the ID from top to bottom in the table or just through a hash table?

**Comment by mschoema** [comment]
By default PostgreSQL will run this query using a sequential scan, but you can also create and index on your ID column to speed up the search if you want.

**Comment by MineRiaaa** [comment]
Got it! Thank you very much!

**Comment by mschoema** [comment]
Note, however, that this type of update query is rather expensive.
Indeed, an `UPDATE` query in PostgreSQL is behind the scenes closely similar to an `INSERT` and a `DELETE`, which means copying the whole trajectory with its newly added point.

If you are working with short trajectories, this could still run fast enough to work for you.
However, if you have large trajectories and need to update often you might see the performance slow down.

For this reason, if you want to efficiently work with real-time data, you should consider using [MEOS](https://www.libmeos.com/) or [PyMEOS](https://github.com/MobilityDB/PyMEOS) to work with the data in-memory and only update your database through occasional `merge` or `appendSequence` call.

**Comment by MineRiaaa** [comment]
Thank you for your explanation; you've helped me a lot! :)

**Comment by mschoema** [comment]
You're welcome, feel free to open other issues if you have more questions
