### ISSUE TITLE
speed along single axis

### ISSUE THREAD

**Issue by renedlog** [MobilityDB/MobilityDB#56]
would like to see derivations of:
speed(tpoint): tfloats

for the individual components (speed per axis)
e.g.:
speed_x()
speed_y()
speed_z()

e.g:
SELECT speed_z(tgeompoint 'Interp=Stepwise;[Point(0 0 0)@2000-01-01, Point(1 1 1)@2000-01-02,
Point(1 0)@2000-01-03]') * 3600 * 24;

**Comment by estebanzimanyi** [comment]
Nice idea ! We already discussed the best possible way to implement it. Our current idea is to implement a derivative function for tfloat which is general and can be used in other contexts and also have the functions getX, getY, getZ of signature tpoint -> tfloat. What do you think ?

**Comment by mschoema** [comment]
Resolved in PR #58.

**Comment by mschoema** [comment]
P.S.: Four SQL functions have been added:

- getX(tgeompoint) -> tfloat
- getY(tgeompoint) -> tfloat
- getZ(tgeompoint) -> tfloat
- derivative(tfloat) -> tfloat

The 'speed along axis' can thus be computed by combining the derivative with the getX, getY or getZ functions:
E.g.: speed along x-axis: derivative(getX(tgeompoint)) -> tfloat
