### ISSUE TITLE
Failure on cross-compiling for Windows using mingw

### ISSUE THREAD

**Issue by evetion** [MobilityDB/MobilityDB#609]
**Describe the bug**
Over at https://github.com/JuliaPackaging/Yggdrasil/pull/9453 I try to cross-compile MEOS for different platforms for the Julia programming language. When cross-compiling for Windows (using mingw), this fails:

```
[ 43%] Building C object meos/postgres/port/CMakeFiles/port.dir/pg_bitutils.c.obj
cd /workspace/srcdir/MobilityDB/build/meos/postgres/port && /opt/bin/x86_64-w64-mingw32-libgfortran5-cxx11/x86_64-w64-mingw32-gcc --sysroot=/opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/ -DGSL_VERSION_STRING=\"2.7.1\" -DMEOS=1 -DMEOS_IS_BIG_ENDIAN=0 -DMOBILITYDB_VERSION_STRING="\"MobilityDB 1.2.0\"" -DNO_FFSL -DNPOINT=0 -DPOSE=0 -DPOSTGIS_PGSQL_VERSION=140 -DPOSTGIS_VERSION_NUMBER=30500 -DPOSTGIS_VERSION_STRING="\"PostGIS 3.5.0\"" -DPOSTGRESQL_VERSION_NUMBER=140200 -DPOSTGRESQL_VERSION_STRING="\"PostgreSQL 14.2\"" -DSYSTEMTZDIR=\"/usr/share/zoneinfo\" -D_USE_MATH_DEFINES @CMakeFiles/port.dir/includes_C.rsp -O3 -DNDEBUG -O2 -fvisibility=hidden   -Wall -Wextra -std=gnu1x -Wunused-parameter -Wno-strict-aliasing -MD -MT meos/postgres/port/CMakeFiles/port.dir/pg_bitutils.c.obj -MF CMakeFiles/port.dir/pg_bitutils.c.obj.d -o CMakeFiles/port.dir/pg_bitutils.c.obj -c /workspace/srcdir/MobilityDB/meos/postgres/port/pg_bitutils.c
/tmp/ccIjAGDk.s: Assembler messages:
/tmp/ccIjAGDk.s:109: Error: incorrect register `%eax' used with `q' suffix
make[2]: *** [meos/postgres/port/CMakeFiles/port.dir/build.make:77: meos/postgres/port/CMakeFiles/port.dir/pg_bitutils.c.obj] Error 1
make[2]: Leaving directory '/workspace/srcdir/MobilityDB/build'
make[1]: *** [CMakeFiles/Makefile2:1192: meos/postgres/port/CMakeFiles/port.dir/all] Error 2
make[1]: Leaving directory '/workspace/srcdir/MobilityDB/build'
make: *** [Makefile:146: all] Error 2
```

**To Reproduce**
The Julia recipe is [here](https://github.com/evetion/Yggdrasil/blob/master/M/MEOS/build_tarballs.jl), but in short this is using a mingw toolchain and the following statements using the 1.2.0 rc1 release using a git checkout.

```bash
cd $WORKSPACE/srcdir/MobilityDB

cmake -B build -DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DMEOS=ON -DHAVE_X86_64_POPCNTQ_EXITCODE="FAILED_TO_RUN" -DHAVE_X86_64_POPCNTQ_EXITCODE__TRYRUN_OUTPUT=
cmake --build build
```

Note I needed to set DHAVE_X86_64_POPCNTQ cache variables because the TRY_RUN cmake is not supported in cross-compilation mode. While related to the failed portion of code, setting the exit code to either zero or one does not make a difference.

Apart from many warnings (overflows) the rest of the codebase seems to cross-compile fine.

**Additional context**
Related to https://github.com/MobilityDB/MobilityDB/issues/513.

**Comment by mschoema** [comment]
Thank you for reporting this issue, I am investigating it.

**Comment by mschoema** [comment]
I just merged a potential fix on our `master` branch. Let us know if this work.
If so, I will backpatch it to `stable-1.2` to include it in the upcoming 1.2.0 release.

**Comment by mschoema** [comment]
Hi, did you manage to check if MEOS compiles with mingw after the commit?
We would like to make sure that this issue is fixed before producing the final v1.2.0 release.

**Comment by evetion** [comment]
Thanks for the patch! I've tested it, and it worked 🎉, but sadly ran into another issue later on. I'm unsure if you support Windows (let alone cross-compiling for it) at all, and whether there's merit in trying to fix things in this way.

That being said, the next error is probably fixed easily with an include statement in the correct place:

```
[ 31%] Building C object meos/src/point/CMakeFiles/point.dir/tpoint_spatialfuncs.c.obj
cd /workspace/srcdir/MobilityDB/build/meos/src/point && /opt/bin/x86_64-w64-mingw32-libgfortran5-cxx11/x86_64-w64-mingw32-gcc --sysroot=/opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/ -DGSL_VERSION_STRING=\"2.7.1\" -DMEOS=1 -DMEOS_IS_BIG_ENDIAN=0 -DMOBILITYDB_VERSION_STRING="\"MobilityDB 1.3.0\"" -DNO_FFSL -DNPOINT=0 -DPOSE=0 -DPOSTGIS_PGSQL_VERSION=140 -DPOSTGIS_VERSION_NUMBER=30500 -DPOSTGIS_VERSION_STRING="\"PostGIS 3.5.0\"" -DPOSTGRESQL_VERSION_NUMBER=140200 -DPOSTGRESQL_VERSION_STRING="\"PostgreSQL 14.2\"" -DSYSTEMTZDIR=\"/usr/share/zoneinfo\" -D_USE_MATH_DEFINES @CMakeFiles/point.dir/includes_C.rsp -O3 -DNDEBUG -O2   -Wall -Wextra -std=gnu1x -Wunused-parameter -Wno-strict-aliasing -MD -MT meos/src/point/CMakeFiles/point.dir/tpoint_spatialfuncs.c.obj -MF CMakeFiles/point.dir/tpoint_spatialfuncs.c.obj.d -o CMakeFiles/point.dir/tpoint_spatialfuncs.c.obj -c /workspace/srcdir/MobilityDB/meos/src/point/tpoint_spatialfuncs.c
/workspace/srcdir/MobilityDB/meos/src/point/tpoint_spatialfuncs.c:47:10: fatal error: lwgeom_pg.h: No such file or directory
 #include <lwgeom_pg.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [meos/src/point/CMakeFiles/point.dir/build.make:287: meos/src/point/CMakeFiles/point.dir/tpoint_spatialfuncs.c.obj] Error 1
make[2]: Leaving directory '/workspace/srcdir/MobilityDB/build'
make[1]: *** [CMakeFiles/Makefile2:1322: meos/src/point/CMakeFiles/point.dir/all] Error 2
make[1]: Leaving directory '/workspace/srcdir/MobilityDB/build'
make: *** [Makefile:146: all] Error 2
```

**Comment by mschoema** [comment]
Glad to hear it worked!
The issue you encountered is related to a list of commits we recently worked on.
The MEOS compilation was broken between the last two commits, but it is fixed again now.
These will not be part of the release though.

**Comment by mschoema** [comment]
Let me cherry-pick the fix to stable-1.2 and you can test the code as it will be in the final release.

**Comment by evetion** [comment]
> Glad to hear it worked! The issue you encountered is related to a list of commits we recently worked on. The MEOS compilation was broken between the last two commits, but it is fixed again now. These will not be part of the release though.

Ah, but indeed, the current master does build on Windows! 👍🏻

**Comment by mschoema** [comment]
MobilityDB 1.2.0 was just released: https://github.com/MobilityDB/MobilityDB/releases/tag/v1.2.0
I believe this is now fixed, but feel free to reopen the issue if you still encounter problems with building MEOS using mingw.
