### ISSUE TITLE
read set of tgeogpointseq in python?

### ISSUE THREAD

**Issue by wendellwt** [MobilityDB/MobilityDB#69]
How do I read a set of tgeogpointseq into Python?

I use a select statement to read mdb trajectories from a table, crop them using atGeometry, and store the result in a pandas dataframe:

```
SELECT fid,
tgeogpointseq(atGeometry(flown_path::tgeompoint, geometry 'SRID=4326;POLYGON ((-95.46386763453484 32.87958717306631, -96.67236372828484 31.39115752282473, -96.03515669703484 30.14512718337609, -93.55224654078484 30.58117925738698, -93.06884810328484 33.26624989076275, -95.46386763453484 32.87958717306631))')::tgeompoint)
    FROM table_with_trajectories
    WHERE fid = 20200805523356 ;
```

Most of the time this works fine (when the result is one tgeogpointseq).  However, if the trajectory exits the polygon and re-enters, the results of the atGeometry() is now a list (or set?) of tgeogpointseq segments.  Mobilitydb returns 'Cannot transform input to a temporal sequence', which is correct since it is not one temporal sequence but several.

How to I tell Python/PostGis/MobilityDB that this is a set of trajectories?  Will it be the MobilityDB version of a MultiLineString?

Thanks,
Wendell
[example.zip](https://github.com/MobilityDB/MobilityDB/files/6287570/example.zip)

**Comment by mschoema** [comment]
Hi Wendell,

Indeed, the result of atGeometry can return a set of sequences.
MobilityDB handles four temporal durations for every type:
- instant (*inst)
- instant set (*i)
- sequence (*seq)
- sequence set (*s)

The type that represents a set of sequences of temporal geography points in MobilityDB is thus *tgeogpoints*.

Also, note that *atGeoemtry* already returns objects of the correct temporal duration (*tgeogpointseq* if the result is a single sequence, and *tgeogpoints* if the result is a set of sequences). Applying the functions *tgeogpointseq* or *tgeogpoints* after *atGeometry* will cast all return values to the same temporal duration. This is the reason why *tgeogpointseq* sometimes returns an error: a set of sequences cannot be cast to a single sequence.

Does this answer your question?

Best regards,
Maxime

**Comment by wendellwt** [comment]
Thank you for the response.  The key point was to read each one as an individual sequence.  Here is what I ended up doing:

```
num = SELECT numSequences(...)
tg_list = [ ]
for n in range(num):

    tg = SELECT tgeogpointseq( sequenceN( ..., n+1))

    tg_list.append(tg)
```
This seems to work.

Thank you,
Wendell

**Comment by mschoema** [comment]
Ah, I see. The function *sequences* will split a sequence set into an array of sequences. You can then use the PostgreSQL *unnest* function to split the array into individual records. This might be easier than looping in python.

`SELECT unnest(sequences(...) FROM ...` 

I hope this can help.

Regards,
Maxime

**Comment by wendellwt** [comment]
Aha!  Yes, that works fine and is much cleaner.  That solution is exactly what I was looking for!

Thank you again,
Wendell

**Comment by mschoema** [comment]
Nice, I'm glad I could help.

Best regards,
Maxime
