### ISSUE TITLE
Can't Compile develop on mingw64 -  SYNCHRONIZE reserved keyword?

### ISSUE THREAD

**Issue by robe2** [MobilityDB/MobilityDB#91]
I'm still having issues compiling develop branch under mingw.  It's better, now it detects my PostgreSQL version and passes the configure step, but breaks at compile:

```
C:/ming64gcc81/projects/mobility/MobilityDB/include/temporal.h:113:3: error: expected identifier before '(' token
   SYNCHRONIZE,
   ^~~~~~~~~~~
make[2]: *** [CMakeFiles/MobilityDB.dir/build.make:97: CMakeFiles/MobilityDB.dir/src/doublen.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1066: CMakeFiles/MobilityDB.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
make: *** No rule to make target 'installcheck'.  Stop.
```

My Cmake configure looks like this:

```
	cmake  -G "MSYS Makefiles" \
		-DLWGEOM_ROOT:PATH=${LIBLWGEOM_PATH} -DPROJ_INCLUDE_DIR:PATH=${PROJ_PATH}/include \
		-DJSONC_INCLUDE_DIR:PATH=${JSON_PATH}/include \
		-DLIBPROTOBUF_INCLUDE_DIR:PATH=${PROTOBUF_PATH}/include \
		 ..
```
Where the various variables are just paths to my compiled versions of things

**Comment by robe2** [comment]
I think SYNCHRONIZE might be a reserved keyword.  If I replace it with something like SYNCHRONIZE_NOCROSS then I get past that step.

**Comment by estebanzimanyi** [comment]
It seems that is indeed the case. In the file \mingw-w64-v9.0.0\mingw-w64-headers\include\winnt.h there is the following definition 
#define SYNCHRONIZE (__MSABI_LONG(0x00100000))
I changed the definition in MobilityDB as you suggested. This is already in the develop branch.

**Comment by estebanzimanyi** [comment]
BTW when using mingw (the traditional 32 bit version) for running the tests it is necessary to create the database and this is done calling initdb. However, this complains about the permissions of the repertory used for initdb.

```
esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$ initdb -D db
The files belonging to this database system will be owned by user "esteban".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory db ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... Europe/Brussels
creating configuration files ... ok
running bootstrap script ... 2021-07-22 11:21:25.046 CEST [3929] FATAL:  data directory "/mnt/c/MobilityDB-develop/build/tmptest/db" has invalid permissions
2021-07-22 11:21:25.046 CEST [3929] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
child process exited with exit code 1
initdb: removing contents of data directory "db"
esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$

```
However, it is reported that `chmod `does not work for windows

```
esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build$ ls
CMakeCache.txt       DartConfiguration.tcl  cmake_install.cmake   mobilitydb--1.0.sql    sqlin
CMakeFiles           Makefile               install_manifest.txt  mobilitydb--1.0.sql.c  tmptest
CTestTestfile.cmake  Testing                libMobilityDB.so      mobilitydb.control
esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build$ cd tmptest
esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$ ls
db  lock  log  out
esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$ ls -l
total 0
drwxrwxrwx 1 esteban esteban 512 Jul 21 15:32 db
drwxrwxrwx 1 esteban esteban 512 Jul 21 14:54 lock
drwxrwxrwx 1 esteban esteban 512 Jul 21 14:54 log
drwxrwxrwx 1 esteban esteban 512 Jul 21 14:54 out
esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$ chmod 700 db
esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$ ls -l
total 0
drwxrwxrwx 1 esteban esteban 512 Jul 21 15:32 db
drwxrwxrwx 1 esteban esteban 512 Jul 21 14:54 lock
drwxrwxrwx 1 esteban esteban 512 Jul 21 14:54 log
drwxrwxrwx 1 esteban esteban 512 Jul 21 14:54 out
esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$
```

Maybe you know how to cope with this issue

**Comment by cvvergara** [comment]
ah, nice catch @robe2 
Without the need to modify postgresql.conf, I can do this in my computer

```
create extension mobilitydb CASCADE;
NOTICE:  installing required extension "postgis"
CREATE EXTENSION
mobtest=# select mobilitydb_version();
  mobilitydb_version   
-----------------------
 MobilityDB 1.0 beta 3
(1 row)
```
Will add a test on the actions that displays the version, on my next PR

**Comment by robe2** [comment]
> 
> 
> BTW when using mingw (the traditional 32 bit version) for running the tests it is necessary to create the database and this is done calling `initdb`. However, this complains about the permissions of the repertory used for initdb.
> 
> ```
> esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$ initdb -D db
> The files belonging to this database system will be owned by user "esteban".
> This user must also own the server process.
> 
> The database cluster will be initialized with locale "C.UTF-8".
> The default database encoding has accordingly been set to "UTF8".
> The default text search configuration will be set to "english".
> 
> Data page checksums are disabled.
> 
> fixing permissions on existing directory db ... ok
> creating subdirectories ... ok
> selecting dynamic shared memory implementation ... posix
> selecting default max_connections ... 20
> selecting default shared_buffers ... 400kB
> selecting default time zone ... Europe/Brussels
> creating configuration files ... ok
> running bootstrap script ... 2021-07-22 11:21:25.046 CEST [3929] FATAL:  data directory "/mnt/c/MobilityDB-develop/build/tmptest/db" has invalid permissions
> 2021-07-22 11:21:25.046 CEST [3929] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
> child process exited with exit code 1
> initdb: removing contents of data directory "db"
> esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$
> ```
> 
> However, it is reported that `chmod `does not work for windows
> 
> ```
> esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build$ ls
> CMakeCache.txt       DartConfiguration.tcl  cmake_install.cmake   mobilitydb--1.0.sql    sqlin
> CMakeFiles           Makefile               install_manifest.txt  mobilitydb--1.0.sql.c  tmptest
> CTestTestfile.cmake  Testing                libMobilityDB.so      mobilitydb.control
> esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build$ cd tmptest
> esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$ ls
> db  lock  log  out
> esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$ ls -l
> total 0
> drwxrwxrwx 1 esteban esteban 512 Jul 21 15:32 db
> drwxrwxrwx 1 esteban esteban 512 Jul 21 14:54 lock
> drwxrwxrwx 1 esteban esteban 512 Jul 21 14:54 log
> drwxrwxrwx 1 esteban esteban 512 Jul 21 14:54 out
> esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$ chmod 700 db
> esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$ ls -l
> total 0
> drwxrwxrwx 1 esteban esteban 512 Jul 21 15:32 db
> drwxrwxrwx 1 esteban esteban 512 Jul 21 14:54 lock
> drwxrwxrwx 1 esteban esteban 512 Jul 21 14:54 log
> drwxrwxrwx 1 esteban esteban 512 Jul 21 14:54 out
> esteban@DESKTOP-9FBND60:/mnt/c/MobilityDB-develop/build/tmptest$
> ```
> 
> Maybe you know how to cope with this issue

Yah chmod isn't supported under windows to my knowledge but I use msys2 for my tool chain  and it understands chmod.  That said I've never had to use that command.  So not sure it really works under msys2 either, might just fake it.  Are you only getting this on 32-bit chain?  I don't ship any new major releases of anything on the 32-bit chain anymore because EDB stopped supporting 32-bit since so few people use it. So 32-bit is only relevant for supporting PG 10 and lower on windows - https://www.enterprisedb.com/download-postgresql-binaries

**Comment by estebanzimanyi** [comment]
I just started using MinGW and therefore it was easy to start with the
traditional/old version. I will install the new mingw-w64 version and try
again soon.

------------------------------------------------------------
Prof. Esteban Zimanyi
Department of Computer & Decision Engineering  (CoDE) CP 165/15
Universite Libre de Bruxelles
Avenue F. D. Roosevelt 50
B-1050 Brussels, Belgium
fax: + 32.2.650.47.13
tel: + 32.2.650.31.85
e-mail: ***@***.***
Internet: http://cs.ulb.ac.be/members/esteban/
------------------------------------------------------------
